### PR TITLE
V2

### PR DESCRIPTION
**Pull request by regis-leray**

### CODE REVIEW

**Comment by soujiro32167** [comment]
Conflict on `CNAME` 🤔

**Comment by regis-leray** [comment]
i changed the domain name to `trampolinelab.io`

**Comment by soujiro32167** [comment]
The intro is much cleaner now! 
I would suggest bringing back the tagline from before:

**Comment by soujiro32167** [comment]
For the blog, only the post about Sergei's talk has content. All the rest lead you back to the blog page - they should not be there

**Comment by regis-leray** [comment]
@soujiro32167 people don't understand `Functional software consulting`.
The goal is to be really explicit about what we are doing. It is some feedback i got from people, not mine.

**Comment by soujiro32167** [comment]
Ok, not `Functional software consulting` then. There is just too much text in there for a headline right now

**Comment by soujiro32167** [comment]
Services page is awesome!

**Comment by soujiro32167** [comment]
The logos are greyscale though?

**Comment by regis-leray** [comment]
@soujiro32167 about the blog we are working on the articles :
- import unsafe article @regis
- create `origin of trampoline` @sergei
- regis & eli speaker at lambda conf global edition 2020 @regis
we can disable them for now if you prefer

**Comment by soujiro32167** [comment]
No love for these?

**Comment by regis-leray** [comment]
@soujiro32167 no since im respecting the design layout we have.

**Comment by soujiro32167** [comment]
@regis-leray I understand. It just looks bad if there are broken links

**Comment by regis-leray** [comment]
@soujiro32167 no problem lets remove them !

**Comment by soujiro32167** [comment]
How about

**Comment by regis-leray** [comment]
@soujiro32167 for me same problem as before we dont understand what we do by reading this.
I totally agree with you there is too much text, we need to reduce it.
But you proposal doesnt resolve the main problem it has to be clear

**Comment by soujiro32167** [comment]
Monad: 



River A&A



Hypotenuse



I like the Hypotenuse approach the best: A short bold headline with longer subheadline to explain what they do.

How about

h1: `High Caliber Software Experts`
h2: `Trampoline is a team of experts specialized in backend systems
focused on scalability and availability`

**Comment by soujiro32167** [comment]
Ziverge:



7mind:



7mind approach is the most minimal, but according to @regis-leray no one will understand what its about. Ziverge is actually close to Hypotenuse and my proposal above

**Comment by regis-leray** [comment]
@soujiro32167 too much expertise in the wording :)

**Pull request merged**
